In [5]:
import pandas as pd
import numpy as np
#Read the CSV or Excel file into a Pandas DataFrame.
df=pd.read_excel(r"C:\Users\hp_Pc\Downloads\array.xlsx")
print(df)

       Name   Age  Marks      City
0      Amit  18.0     85      Pune
1      Neha  19.0     90    Mumbai
2       Raj   NaN     78      Pune
3      Amit  18.0     85      Pune
4      Puja  21.0     79     Delhi
5   Reshma   22.0     80    Mumbai
6    Rishav  20.0     79  Baramati
7      Anya  17.0     89  Hadapsar
8     Gauri  16.0     98    Pimpri
9    Manasi  15.0     96      Wapi
10    Kajal  24.0     94       Div

In [6]:
#Display the first few records
print("First five records only:")
print(df.head())

First five records only:
   Name   Age  Marks    City
0  Amit  18.0     85    Pune
1  Neha  19.0     90  Mumbai
2   Raj   NaN     78    Pune
3  Amit  18.0     85    Pune
4  Puja  21.0     79   Delhi

In [7]:
#Display information about the dataset.
print("dataset information:")
print(df.info())

dataset information:
<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    11 non-null     str
 1   Age     10 non-null     float64
 2   Marks   11 non-null     int64
 3   City    11 non-null     str
dtypes: float64(1), int64(1), str(2)
memory usage: 484.0 bytes
None

In [8]:
#Check for missing values.
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 1

In [9]:
#Handle missing values using an appropriate method.
df.fillna(df.mean(numeric_only=True), inplace=True)

       Name   Age  Marks      City
0      Amit  18.0     85      Pune
1      Neha  19.0     90    Mumbai
2       Raj  19.0     78      Pune
3      Amit  18.0     85      Pune
4      Puja  21.0     79     Delhi
5   Reshma   22.0     80    Mumbai
6    Rishav  20.0     79  Baramati
7      Anya  17.0     89  Hadapsar
8     Gauri  16.0     98    Pimpri
9    Manasi  15.0     96      Wapi
10    Kajal  24.0     94       Div

In [10]:
#Identify and remove duplicate records.
print("Number of duplicate records:", df.duplicated().sum())

Number of duplicate records: 1

In [11]:
#Convert data types wherever required.
df['Name'] = df['Name'].astype('string')

In [12]:
#Perform basic data cleaning.
df.columns = df.columns.str.strip()

In [13]:
#Display the preprocessed dataset.
display(df)

       Name   Age  Marks      City
0      Amit  18.0     85      Pune
1      Neha  19.0     90    Mumbai
2       Raj  19.0     78      Pune
3      Amit  18.0     85      Pune
4      Puja  21.0     79     Delhi
5   Reshma   22.0     80    Mumbai
6    Rishav  20.0     79  Baramati
7      Anya  17.0     89  Hadapsar
8     Gauri  16.0     98    Pimpri
9    Manasi  15.0     96      Wapi
10    Kajal  24.0     94       Div

In [14]:
#Display the final dataset information.
print("Final Dataset Information")

print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

print("\nColumn Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Records:")
print(df.duplicated().sum())

Final Dataset Information
Number of Rows: 11
Number of Columns: 4

Column Information:
<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    11 non-null     string
 1   Age     11 non-null     float64
 2   Marks   11 non-null     int64
 3   City    11 non-null     str
dtypes: float64(1), int64(1), str(1), string(1)
memory usage: 484.0 bytes

Missing Values:
Name     0
Age      0
Marks    0
City     0
dtype: int64

Duplicate Records:
1